version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'topic-test:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka_exporter:
    image: danielqsj/kafka-exporter
    ports:
      - '9308:9308'
    depends_on:
      - kafka
    restart: always
 
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/Utils/scripts/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka_exporter
      - alertmanager
    restart: always
 
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    depends_on:
      - kafka_exporter
 
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - $PWD/plugin:/var/lib/grafana/plugins
    depends_on:
      - prometheus
    volumes:
      - $PWD/plugin:/var/lib/grafana/plugins

